name: code_uml
description: This package help you build UML diagram. You have to copy result from result file and paste in PlantUML
version: 1.0.2
homepage: https://github.com/chashkovdaniil/graph_analyzer/
repository: https://github.com/chashkovdaniil/graph_analyzer/

environment:
  sdk: '>=3.0.0 <4.0.0'

executables: 
  code_uml:

dependencies:
  analyzer: ^6.4.1
  args: ^2.4.2
  io: ^1.0.4
  path: ^1.9.0

dev_dependencies:
  lints: ^2.0.0   

topics:
  - analysis
  - uml
  - diagram
  - generate